// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadTcpBpf returns the embedded CollectionSpec for TcpBpf.
func LoadTcpBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpBpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TcpBpf: %w", err)
	}

	return spec, err
}

// LoadTcpBpfObjects loads TcpBpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TcpBpfObjects
//	*TcpBpfPrograms
//	*TcpBpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTcpBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTcpBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TcpBpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpBpfSpecs struct {
	TcpBpfProgramSpecs
	TcpBpfMapSpecs
	TcpBpfVariableSpecs
}

// TcpBpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpBpfProgramSpecs struct {
	OvsCtExecute *ebpf.ProgramSpec `ebpf:"ovs_ct_execute"`
}

// TcpBpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpBpfMapSpecs struct {
}

// TcpBpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpBpfVariableSpecs struct {
}

// TcpBpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTcpBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpBpfObjects struct {
	TcpBpfPrograms
	TcpBpfMaps
	TcpBpfVariables
}

func (o *TcpBpfObjects) Close() error {
	return _TcpBpfClose(
		&o.TcpBpfPrograms,
		&o.TcpBpfMaps,
	)
}

// TcpBpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTcpBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpBpfMaps struct {
}

func (m *TcpBpfMaps) Close() error {
	return _TcpBpfClose()
}

// TcpBpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTcpBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpBpfVariables struct {
}

// TcpBpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTcpBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpBpfPrograms struct {
	OvsCtExecute *ebpf.Program `ebpf:"ovs_ct_execute"`
}

func (p *TcpBpfPrograms) Close() error {
	return _TcpBpfClose(
		p.OvsCtExecute,
	)
}

func _TcpBpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpbpf_bpfeb.o
var _TcpBpfBytes []byte
